[package]
name = "g_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = {version = "0.26.0"} 
ash-window = "0.7"
winit = "0.25.0"
image = "0.10.4"